version: "3"

services:
  laravel:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs_app
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
